grpc:
  client:
    postService:
      address: posts-service:9090
      negotiation-type: plaintext
spring:
  application:
    name: feeds-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: feeds-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:postgresql://postgres:5432/feeds
    username: tuanha
    password: tuanha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: redis
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8081/eureka
  instance:
    hostname: feeds-service
server:
  port: 8003
tracing:
  url: http://jaeger:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0